name: Test application with Unittest

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./neural_love_api

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run tests with Unittest
      shell: bash
      run: |
        python -m unittest discover ../tests
